ansible_host_key_checking: False
ansible_ssh_user: admin
ansible_ssh_pass: admin
ansible_ssh_common_args:  '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no - KexAlgorithms=+diffie-hellman-group1-sha1'
ansible_host_key_auto_add: yes
remote_user: mike

license_dir: /root/files/{{vsr_name}}
qcow2_dir: /root/files/{{vsr_name}}

mgmt_ip: '{{vsr_mgmt}}'
mgmt_nm: 24
mgmt_gw: '{{vsr_mgmt_gw}}'
mgmt_static_rt_list:
    - 0.0.0.0/1
    - 128.0.0.0/1

