#[bof_config]
vm_name: R1
vsr_mgmt: 10.0.12.15
vsr_mgmt_gw: 10.0.12.1

#[base_config_kvm]
numbr: 5
vmname: R1
qcow_image: R1
desc: R1_XML_FILE
bridges: 
    - MGMT-BR
    - R1R5-BR
    - R1R2-BR
    - R1R3-BR
    - R1R4-BR

#[base_config_file]
ifcount: 4
routername: P1
phy_interfaces:
    - int_name: P1-to-P2 
      ip_addr: 1.1.2.1/30
      port: 1/1/c2/1
    - int_name: P1-to-P3
      ip_addr: 1.1.3.1/30
      port: 1/1/c3/1 
    - int_name: P1-to-P4 
      ip_addr: 1.1.4.1/30 
      port: 1/1/c4/1
    - int_name: P1-to-PE1 
      ip_addr: 1.1.5.1/30
      port: 1/1/c1/1
loopbacks:
    - loop_name: Loopback1
      ip_addr: 100.1.1.1/32
    - loop_name: Loopback2
      ip_addr: 100.2.2.1/32
