#[bof_config]
vm_name: R1
vsr_mgmt: 10.0.12.15
vsr_mgmt_gw: 10.0.12.1

#[base_config_kvm]
numbr: 5
vmname: R1
qcow_image: R1
desc: R1_XML_FILE
bridges: 
    - MGMT-BR
    - R1R5-BR
    - R1R2-BR
    - R1R3-BR
    - R1R4-BR

#[base_config_file]
ifcount: 4
routername: P1
Intf1: P1-to-P2
Address1: 1.1.2.1/30
Port1: 1/1/c2/1 
Intf2: P1-to-P3
Address2: 1.1.3.1/30
Port2: 1/1/c3/1 
Intf3: P1-to-P4
Address3: 1.1.4.1/30
Port3: 1/1/c4/1 
Intf4: P1-to-PE1
Address4: 1.1.5.1/30
Port4: 1/1/c1/1