#[bof_config]
vm_name: R10
vsr_mgmt: 10.0.12.24
vsr_mgmt_gw: 10.0.12.1


#[base_config_kvm]
numbr: 3
vmname: R10
qcow_image: R10
desc: R10_XML_FILE
bridges: 
    - MGMT-BR
    - MGMT-BR
    - R6R10-BR
uuid: 1d83d920-5d95-4dd0-8ff8-79c82c762787

#[base_config_file]
routername: CE2
phy_interfaces:
    - int_name: To-PE2 
      ip_addr: 1.6.10.2/30 
      port: 1/1/c2/1
loopbacks:
    - loop_name: Loopback1 
      ip_addr: 100.1.1.10/32
    - loop_name: Loopback2 
      ip_addr: 100.2.2.10/32
sys_ip:
    - ip_addr: 172.17.0.10/32