#[bof_config]
vm_name: R11
vsr_mgmt: 10.0.12.25
vsr_mgmt_gw: 10.0.12.1


#[base_config_kvm]
numbr: 3
vmname: R11
qcow_image: R11
desc: R11_XML_FILE
bridges: 
    - MGMT-BR
    - MGMT-BR
    - R7R11-BR
uuid: 8db35647-0dd3-44d8-a8a3-ab490f9924c4

#[base_config_file]
routername: CE3
phy_interfaces:
    - int_name: To-PE3 
      ip_addr: 1.7.11.2/30
      port: 1/1/c2/1
loopbacks:
    - loop_name: Loopback1 
      ip_addr: 100.1.1.11/32
    - loop_name: Loopback2
      ip_addr: 100.2.2.11/32
sys_ip:
    - ip_addr: 172.18.0.11/32