#[bof_config]
vm_name: R12
vsr_mgmt: 10.0.12.26
vsr_mgmt_gw: 10.0.12.1

#[base_config_kvm]
numbr: 3
vmname: R12
qcow_image: R12
desc: R12_XML_FILE
bridges: 
    - MGMT-BR
    - MGMT-BR
    - R8R12-BR

#[base_config_file]
ifcount: 1
routername: CE4
networkcfg:
    - [ CE4-to-PE4, 1.8.12.2/30, 1/1/c2/1 ]