#[bof_config]
vm_name: R12
vsr_mgmt: 10.0.12.26
vsr_mgmt_gw: 10.0.12.1

#[base_config_kvm]
numbr: 3
vmname: R12
qcow_image: R12
desc: R12_XML_FILE
bridges: 
    - MGMT-BR
    - MGMT-BR
    - R8R12-BR
uuid: 0348a9b7-0e9f-49ae-b500-a10eaa259355

#[base_config_file]
routername: CE4
phy_interfaces:
    - int_name: To-PE4
      ip_addr: 1.8.12.2/30
      port: 1/1/c2/1
loopbacks:
    - loop_name: Loopback1
      ip_addr: 100.1.1.12/32
    - loop_name: Loopback2
      ip_addr: 100.2.2.12/32
sys_ip:
    - ip_addr: 172.19.0.12/32