#[bof_config]
vm_name: R2
vsr_mgmt: 10.0.12.16
vsr_mgmt_gw: 10.0.12.1

#[base_config_kvm]
numbr: 5
vmname: R2
qcow_image: R2
desc: R2_XML_FILE
br1: MGMT-BR
br2: R2R6-BR
br3: R1R2-BR
br4: R2R4-BR
br5: R2R3-BR


#[base_config_file]
ifcount: 4
routername: P2
Intf1: P2-to-P1
Address1: 1.1.2.2/30
Port1: 1/1/c2/1 
Intf2: P2-to-P3
Address2: 1.2.3.1/30
Port2: 1/1/c4/1 
Intf3: P2-to-P4
Address3: 1.2.4.1/30
Port3: 1/1/c3/1 
Intf4: P2-to-PE2
Address4: 1.2.6.1/30
Port4: 1/1/c1/1