#[bof_config]
vm_name: R2
vsr_mgmt: 10.0.12.16
vsr_mgmt_gw: 10.0.12.1

#[base_config_kvm]
numbr: 5
vmname: R2
qcow_image: R2
desc: R2_XML_FILE
bridges: 
    - MGMT-BR
    - R2R6-BR
    - R1R2-BR
    - R2R4-BR
    - R2R3-BR


#[base_config_file]
ifcount: 4
routername: P2
networkcfg:
    - [ P2-to-P1, 1.1.2.2/30, 1/1/c2/1 ]
    - [ P2-to-P3, 1.2.3.1/30, 1/1/c4/1 ]
    - [ P2-to-P4, 1.2.4.1/30, 1/1/c3/1 ]
    - [ P2-to-PE2, 1.2.6.1/30, 1/1/c1/1 ]
