#[bof_config]
vm_name: R2
vsr_mgmt: 10.0.12.16
vsr_mgmt_gw: 10.0.12.1

#[base_config_kvm]
numbr: 5
vmname: R2
qcow_image: R2
desc: R2_XML_FILE
bridges: 
    - MGMT-BR
    - R2R6-BR
    - R1R2-BR
    - R2R4-BR
    - R2R3-BR
uuid: a65eed44-83ed-4343-bd4a-9270f3acdc7e

#[base_config_file]
routername: P2
phy_interfaces:
  - int_name: To-P1 
    ip_addr: 1.1.2.2/30 
    port: 1/1/c2/1
  - int_name: To-P3 
    ip_addr: 1.2.3.1/30 
    port: 1/1/c4/1
  - int_name: To-P4 
    ip_addr: 1.2.4.1/30 
    port: 1/1/c3/1
  - int_name: To-PE2 
    ip_addr: 1.2.6.1/30 
    port: 1/1/c1/1
loopbacks:
  - loop_name: Loopback1 
    ip_addr: 100.1.1.2/32
  - loop_name: Loopback2 
    ip_addr: 100.2.2.2/32
sys_ip:
    - ip_addr: 172.17.0.2/32