#[bof_config]
vm_name: R3
vsr_mgmt: 10.0.12.17
vsr_mgmt_gw: 10.0.12.1

#[base_config_kvm]
numbr: 5
vmname: R3
qcow_image: R3
desc: R3_XML_FILE
bridges: 
    - MGMT-BR
    - R3R7-BR
    - R3R4-BR
    - R1R3-BR
    - R2R3-BR

#[base_config_file]
ifcount: 4
routername: P3
phy_interfaces:
    - int_name: P3-to-P1 
      ip_addr: 1.1.3.2/30 
      port: 1/1/c3/1
    - int_name: P3-to-P2 
      ip_addr: 1.2.3.2/30 
      port: 1/1/c4/1
    - int_name: P3-to-P4 
      ip_addr: 1.3.4.1/30 
      port: 1/1/c2/1
    - int_name: P3-to-PE3 
      ip_addr: 1.3.7.1/30 
      port: 1/1/c1/1
loopbacks:
    - loop_name: Loopback1 
      ip_addr: 100.1.1.3/32
    - loop_name: Loopback2 
      ip_addr: 100.2.2.3/32