#[bof_config]
vm_name: R3
vsr_mgmt: 10.0.12.17
vsr_mgmt_gw: 10.0.12.1

#[base_config_kvm]
numbr: 5
vmname: R3
qcow_image: R3
desc: R3_XML_FILE
br1: MGMT-BR
br2: R3R7-BR
br3: R3R4-BR
br4: R1R3-BR
br5: R2R3-BR

#[base_config_file]
ifcount: 4
routername: P3
Intf1: P3-to-P1
Address1: 1.1.3.2/30
Port1: 1/1/c3/1 
Intf2: P3-to-P2
Address2: 1.2.3.2/30
Port2: 1/1/c4/1 
Intf3: P3-to-P4
Address3: 1.3.4.1/30
Port3: 1/1/c2/1 
Intf4: P3-to-PE3
Address4: 1.3.7.1/30
Port4: 1/1/c1/1