#[bof_config]
vm_name: R4
vsr_mgmt: 10.0.12.18
vsr_mgmt_gw: 10.0.12.1

#[base_config_kvm]
numbr: 5
vmname: R4
qcow_image: R4
desc: R4_XML_FILE
bridges: 
    - MGMT-BR
    - R4R8-BR
    - R3R4-BR
    - R2R4-BR
    - R1R4-BR 

#[base_config_file]
ifcount: 4
routername: P4
networkcfg:
    - [ P4-to-P1, 1.1.4.2/30, 1/1/c4/1 ]
    - [ P4-to-P2, 1.2.4.2/30, 1/1/c3/1 ]
    - [ P4-to-P3, 1.3.4.2/30, 1/1/c2/1 ]
    - [ P4-to-PE4, 1.4.8.1/30, 1/1/c1/1 ]