#[bof_config]
vm_name: R4
vsr_mgmt: 10.0.12.18
vsr_mgmt_gw: 10.0.12.1

#[base_config_kvm]
numbr: 5
vmname: R4
qcow_image: R4
desc: R4_XML_FILE
bridges: 
    - MGMT-BR
    - R4R8-BR
    - R3R4-BR
    - R2R4-BR
    - R1R4-BR 

#[base_config_file]
ifcount: 4
routername: P4
Intf1: P4-to-P1
Address1: 1.1.4.2/30
Port1: 1/1/c4/1 
Intf2: P4-to-P2
Address2: 1.2.4.2/30
Port2: 1/1/c3/1 
Intf3: P4-to-P3
Address3: 1.3.4.2/30
Port3: 1/1/c2/1 
Intf4: P4-to-PE4
Address4: 1.4.8.1/30
Port4: 1/1/c1/1