#[bof_config]
vm_name: R5
vsr_mgmt: 10.0.12.19
vsr_mgmt_gw: 10.0.12.1

#[base_config_kvm]
numbr: 4
vmname: R5
qcow_image: R5
desc: R5_XML_FILE
bridges: 
    - MGMT-BR
    - R1R5-BR
    - R5R9-BR
    - R5R6-BR

#[base_config_file]
ifcount: 3
routername: PE1
networkcfg:
    - [ PE1-to-P1, 1.1.5.2/30, 1/1/c1/1 ]
    - [ PE1-to-PE2, 1.5.6.1/30, 1/1/c3/1 ]
    - [ PE1-to-CE1, 1.5.9.1/30, 1/1/c2/1 ]