#[bof_config]
vm_name: R5
vsr_mgmt: 10.0.12.19
vsr_mgmt_gw: 10.0.12.1

#[base_config_kvm]
numbr: 4
vmname: R5
qcow_image: R5
desc: R5_XML_FILE
bridges:
  - MGMT-BR
  - R1R5-BR
  - R5R9-BR
  - R5R6-BR
uuid: fbbb4c1a-e90f-467b-a2ca-6c39411496b4

#[base_config_file]
routername: PE1
phy_interfaces:
  - int_name: To-P1
    ip_addr: 1.1.5.2/30
    port: 1/1/c1/1
  - int_name: To-PE2
    ip_addr: 1.5.6.1/30
    port: 1/1/c3/1
  - int_name: To-CE1
    ip_addr: 1.5.9.1/30
    port: 1/1/c2/1
loopbacks:
  - loop_name: Loopback1
    ip_addr: 100.1.1.5/32
  - loop_name: Loopback2
    ip_addr: 100.2.2.5/32
sys_ip:
  - ip_addr: 172.16.0.5/32
