#[bof_config]
vm_name: R7
vsr_mgmt: 10.0.12.21
vsr_mgmt_gw: 10.0.12.1

#[base_config_kvm]
vmname: R7
qcow_image: R7
desc: R7_XML_FILE
bridges:
  - MGMT-BR
  - R3R7-BR
  - R7R11-BR
  - R7R8-BR
uuid: 365ea1db-d437-46aa-bb5a-458fb0994d29

#[base_config_file]
routername: PE3
phy_interfaces:
  - int_name: To-P3
    ip_addr: 1.3.7.2/30
    port: 1/1/c1/1
  - int_name: To-PE4
    ip_addr: 1.7.8.1/30
    port: 1/1/c3/1
  - int_name: To-CE3
    ip_addr: 1.7.11.1/30
    port: 1/1/c2/1
loopbacks:
  - loop_name: Loopback1
    ip_addr: 100.1.1.7/32
  - loop_name: Loopback2
    ip_addr: 100.2.2.7/32
sys_ip:
  - ip_addr: 172.18.0.7/32
