#[bof_config]
vm_name: R7
vsr_mgmt: 10.0.12.21
vsr_mgmt_gw: 10.0.12.1

#[base_config_kvm]
numbr: 4
vmname: R7
qcow_image: R7
desc: R7_XML_FILE
bridges: 
    - MGMT-BR
    - R3R7-BR
    - R7R11-BR
    - R7R8-BR

#[base_config_file]
ifcount: 3
routername: PE3
phy_interfaces:
    - int_name: PE3-to-P3
      ip_addr: 1.3.7.2/30
      port: 1/1/c1/1 
    - int_name: PE3-to-PE4
      ip_addr: 1.7.8.1/30
      port: 1/1/c3/1
    - int_name: PE3-to-CE3
      ip_addr: 1.7.11.1/30
      port: 1/1/c2/1
loopbacks:
    - loop_name: Loopback1
      ip_addr: 100.1.1.7/32
    - loop_name: Loopback2
      ip_addr: 100.2.2.7/32