#[bof_config]
vm_name: R8
vsr_mgmt: 10.0.12.22
vsr_mgmt_gw: 10.0.12.1

#[base_config_kvm]
numbr: 4
vmname: R8
qcow_image: R8
desc: R8_XML_FILE
br1: MGMT-BR
br2: R4R8-BR
br3: R8R12-BR
br4: R7R8-BR

#[base_config_file]
ifcount: 3
routername: PE4
Intf1: PE4-to-P4
Address1: 1.4.8.2/30
Port1: 1/1/c1/1 
Intf2: PE4-to-PE3
Address2: 1.7.8.2/30
Port2: 1/1/c3/1 
Intf3: PE4-to-CE4
Address3: 1.8.12.1/30
Port3: 1/1/c2/1 