#[bof_config]
vm_name: R8
vsr_mgmt: 10.0.12.22
vsr_mgmt_gw: 10.0.12.1

#[base_config_kvm]
numbr: 4
vmname: R8
qcow_image: R8
desc: R8_XML_FILE
bridges: 
    - MGMT-BR
    - R4R8-BR
    - R8R12-BR
    - R7R8-BR

#[base_config_file]
ifcount: 3
routername: PE4
networkcfg:
    - [ PE4-to-P4, 1.4.8.2/30, 1/1/c1/1 ]
    - [ PE4-to-PE3, 1.7.8.2/30, 1/1/c3/1 ]
    - [ PE4-to-CE4, 1.8.12.1/30, 1/1/c2/1 ]