---
- name: Install required packages
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - git
      - libvirt
      - qemu-kvm
      - libvirt-python
      - libguestfs-tools
      - virt-install
      - wget
      - curl
      - tcpdump
      - python3-pip

- name: Install PIP Dependencies
  pip:
    name:
      - ruamel.yaml<=0.15
    executable: pip3
    state: latest
    